apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: louisscrf/auth-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "sqlite:////app/db/auth.db"
            - name: JWT_SECRET
              value: "change-me"
            - name: CORS_ORIGINS
              value: "http://devops.local"

          volumeMounts:
            - name: auth-storage
              mountPath: /app/db
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 5

      volumes:
        - name: auth-storage
          persistentVolumeClaim:
            claimName: auth-pvc
